version: '3.8'

services:
  #Github: https://github.com/juank20097/Django_Form   ///   docker build -t django_comite:latest .
  django:
    image: django_comite
    container_name: django_comite
    restart: always
    volumes:
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=diccionario
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=192.168.12.202
      - DB_PORT=5432

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - staticfiles:/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django

volumes:
  staticfiles:
