version: '3.8'

services:
#Github: https://github.com/juank20097/Django_Form   ///   docker build -t django_comite:latest .
  django:
    image: django_comite
    container_name: django_comite
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=diccionario
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=192.168.12.202
      - DB_PORT=5432

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # Exponer el puerto 80 al host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Montar la configuración de Nginx
    depends_on:
      - django  # Asegurarse de que Django esté corriendo antes de iniciar Nginx
