# Generated by Django 4.2.3 on 2023-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analista_Calidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicativo_Afectado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicativo_Desplegado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QAStandBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Ejecucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
