# Generated by Django 4.2.7 on 2024-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_componente_objeto_esquema_objetos_bdd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esquema',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='esquema',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
