# Generated by Django 4.2.3 on 2023-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_comite',
            fields=[
                ('id_comite', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_del_requerimiento', models.DateTimeField(null=True)),
                ('tipo_paso_produccion', models.CharField(choices=[('planificado', 'Planificado'), ('emergente', 'Emergente')], max_length=255, null=True)),
                ('numero_requerimiento', models.CharField(max_length=255, null=True)),
                ('estado_flujo_req', models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('QA', 'QA'), ('Negocio', 'Negocio')], max_length=255, null=True)),
                ('breve_descripcion_req', models.CharField(max_length=255, null=True)),
                ('tipo_despliegue', models.CharField(choices=[('APP', 'APP'), ('APP-BDD', 'APP-BDD'), ('BDD', 'BDD')], max_length=255, null=True)),
                ('tipo_script', models.CharField(choices=[('DML+DDL', 'DML+DDL'), ('DML', 'DML'), ('DDL', 'DDL'), ('DCL', 'DCL')], max_length=255, null=True)),
                ('tipo_bdd', models.CharField(choices=[('Oracle', 'Oracle'), ('Postgresql', 'Postgresql'), ('DB2', 'DB2')], max_length=255, null=True)),
                ('formulario_menus', models.BooleanField(default=False)),
                ('lider', models.CharField(max_length=255, null=True)),
                ('desarrollador', models.CharField(max_length=255, null=True)),
                ('negocio', models.CharField(max_length=255, null=True)),
                ('fecha_asignacion_calidad', models.DateTimeField(null=True)),
                ('dias_planificados_pruebas', models.IntegerField(null=True)),
                ('tester', models.CharField(max_length=255, null=True)),
                ('qa_stand_by', models.BooleanField(default=False)),
                ('aplicativos_desplegados', models.CharField(max_length=255, null=True)),
                ('aplicativos_afectados', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(choices=[('No aplicado en producción', 'No aplicado en producción'), ('Por aplicar en producción', 'Por aplicar en producción'), ('Aplicado en producción', 'Aplicado en producción'), ('Reversado', 'Reversado')], max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(null=True)),
                ('responsable_ejecucion', models.CharField(max_length=255, null=True)),
                ('fecha_ejecucion', models.DateTimeField(null=True)),
                ('tiempo_ejecucion', models.FloatField(null=True)),
                ('fecha_reversa', models.DateTimeField(null=True)),
                ('observaciones_paso_produccion', models.CharField(max_length=255, null=True)),
                ('fecha_comite', models.DateTimeField(null=True)),
                ('afectacion_objetos_core', models.BooleanField(default=False)),
                ('fecha_asignacion_seguridad', models.DateTimeField(null=True)),
                ('fecha_real_asignacion_calidad', models.DateTimeField(null=True)),
                ('fecha_real_asignacion_seguridad', models.DateTimeField(null=True)),
                ('fecha_real_asignacion_plataforma', models.DateTimeField(null=True)),
                ('observacion_calidad', models.CharField(max_length=255, null=True)),
                ('responsable_creacion_branch', models.CharField(max_length=255, null=True)),
                ('responsable_creacion_tag', models.CharField(max_length=255, null=True)),
                ('fecha_creacion_tag', models.DateTimeField(null=True)),
                ('fecha_creacion_branch', models.DateTimeField(null=True)),
                ('fecha_ejecucion_pruebas', models.DateTimeField(null=True)),
                ('analista_calidad_ejecucion_pruebas', models.BooleanField(default=False)),
                ('autorizador_paso_produccion', models.BooleanField(default=False)),
            ],
        ),
    ]
