# Generated by Django 4.2.3 on 2023-07-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_comite',
            new_name='Comite',
        ),
    ]
