# Generated by Django 4.2.3 on 2023-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='fecha_asignacion_calidad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_asignacion_seguridad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_comite',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_creacion_branch',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_creacion_tag',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_del_requerimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_ejecucion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_ejecucion_pruebas',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_hora',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_real_asignacion_calidad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_real_asignacion_plataforma',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_real_asignacion_seguridad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='fecha_reversa',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='base_de_datos',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('Postgresql', 'Postgresql'), ('DB2', 'DB2')], max_length=100, null=True),
        ),
    ]
